[build]
  publish = "public"
  command = """
  echo "Writing service account credentials to file..."
  echo $GOOGLE_CREDENTIALS_JSON > service-account.json
  echo "Setting GOOGLE_APPLICATION_CREDENTIALS environment variable..."
  export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
  echo "Installing dependencies..."
  pip install -r requirements.txt
  echo "Starting Gunicorn server..."
  gunicorn --bind 0.0.0.0:$PORT functions.app:app
  """

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"

[build.environment]
  PORT = "8000"